//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_SHAGIAHMETOV_AMIN_AIRATOVICH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match_History
    {
        public int Id { get; set; }
        public Nullable<int> Id_Players { get; set; }
        public Nullable<int> Id_Tournament { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<int> Count_Kill { get; set; }
        public string Count_Help { get; set; }
        public Nullable<System.DateTime> Date_Match { get; set; }
    
        public virtual Games_Players Games_Players { get; set; }
    }
}
