//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_SHAGIAHMETOV_AMIN_AIRATOVICH
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TournamentDB_422_SHAGIAHMETOV_AMIN_AIRATOVICHEntities : DbContext
    {
        public TournamentDB_422_SHAGIAHMETOV_AMIN_AIRATOVICHEntities()
            : base("name=TournamentDB_422_SHAGIAHMETOV_AMIN_AIRATOVICHEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achivments> Achivments { get; set; }
        public virtual DbSet<Comands> Comands { get; set; }
        public virtual DbSet<Format_Game> Format_Game { get; set; }
        public virtual DbSet<Game> Game { get; set; }
        public virtual DbSet<Games_Players> Games_Players { get; set; }
        public virtual DbSet<Match_History> Match_History { get; set; }
        public virtual DbSet<Order_Players> Order_Players { get; set; }
        public virtual DbSet<Orders_Comands> Orders_Comands { get; set; }
        public virtual DbSet<Player_Achivments> Player_Achivments { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<Players_Erning> Players_Erning { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<State_Tournament> State_Tournament { get; set; }
        public virtual DbSet<Status_Order> Status_Order { get; set; }
        public virtual DbSet<Status_Player_in_Tournament> Status_Player_in_Tournament { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tournament> Tournament { get; set; }
        public virtual DbSet<Tournament_Category> Tournament_Category { get; set; }
        public virtual DbSet<Toutnament_Result> Toutnament_Result { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
