//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_SHAGIAHMETOV_AMIN_AIRATOVICH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Players
    {
        public int Id { get; set; }
        public Nullable<int> Id_Players { get; set; }
        public Nullable<int> Id_Tournament { get; set; }
        public Nullable<int> Id_Status { get; set; }
    
        public virtual Games_Players Games_Players { get; set; }
        public virtual Status_Order Status_Order { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
