//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_SHAGIAHMETOV_AMIN_AIRATOVICH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player_Achivments
    {
        public int Id { get; set; }
        public Nullable<int> Player_Id { get; set; }
        public Nullable<int> Achivment_Id { get; set; }
    
        public virtual Achivments Achivments { get; set; }
        public virtual Games_Players Games_Players { get; set; }
    }
}
