//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tournament_422_SHAGIAHMETOV_AMIN_AIRATOVICH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.Order_Players = new HashSet<Order_Players>();
            this.Players_Erning = new HashSet<Players_Erning>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Id_Category { get; set; }
        public Nullable<System.DateTime> Start_date { get; set; }
        public Nullable<int> Game_Id { get; set; }
        public Nullable<int> Fromat_Id { get; set; }
        public Nullable<int> Id_State { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Prize_Fond { get; set; }
    
        public virtual Format_Game Format_Game { get; set; }
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Players> Order_Players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Players_Erning> Players_Erning { get; set; }
        public virtual State_Tournament State_Tournament { get; set; }
        public virtual Tournament_Category Tournament_Category { get; set; }
    }
}
